apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-notification-deployment
  labels:
    app: monitoring-notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-notification-deployment
  template:
    metadata:
      labels:
        app: monitoring-notification-deployment
    spec:
      containers:
        - name: monitoring-notification-server-backend
          image: docker.io/groundlight/monitoring-notification-server-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      containers:
        - name: monitoring-notification-server-frontend
          image: docker.io/groundlight/monitoring-notification-server-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
kind: Service 
apiVersion: v1 
metadata:
  name: monitoring-notification-service
spec:
  type: NodePort
  selector:
    app: monitoring-notification-deployment 

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30163
      targetPort: 3000